---

services:
  fortiweb-exporter:
    build: .
    pull_policy: never
    image: fortiweb-exporter:latest
    container_name: fortiweb-exporter
    restart: unless-stopped
    ports:
      - "9633:9633"
    volumes:
      - ./config.yml:/etc/fortiweb-exporter/config.yml:ro
