fortiweb:
  fwb-01.example.com:
    url: "https://10.0.1.10"
    username: "admin"
    password: "changeme"
    vdom: "root"
    insecure_skip_verify: true
  fwb-02.example.com:
    url: "https://10.0.2.10"
    username: "admin"
    password: "changeme"
    vdom: "root"
    insecure_skip_verify: true
listen_address: ":9633"
